baseURL = 'https://somc.club/'
languageCode = 'en-us'
title = 'SoMC: Social Minecraft'
theme = 'arcana'
copyright = "© SoMC. All rights reserved"

[params]
favicon="favicon.png"
[params.sass]
outputStyle = "compressed"
precision = 6

#[build]
#writeStats = true